#!/bin/bash

bug=$1
tgl=$(date)
dc=$(httping -c 5 ${bug} | grep connected | cut -d= -f3 | grep -c ms)

if [[ $dc = "5" ]]; then
   echo -e "Connected"
else
   echo -e "No Internet"
   modemnet -r
   echo -e "Reboot Modem : ${tgl}" >> /root/log.txt
fi

